pipeline:
  name: "MyPipeline"
  actions:
    -
        branch: dev
        repo: "/Users/tlongo/projects/kotlin/notes"
        type: checkout

    -
        type: build
        command: ./gradlew build -x test

    - 
        type: deploy
        source: "notes/build/libs/notes-0.0.1-SNAPSHOT.jar"
        destination: "/Users/tlongo/temp/deploymentdest/notes.jar"
        tool: cp
